import Head from "next/head";
import peopleJson from "../../libs/people-data";
import Header from "../components/header";

export default function Person({
  name,
  about,
  balance,
  age,
  eyeColor,
  phone,
  email,
  address,
}) {
  return (
    <div>
      <Head>
        <title>People</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main style={{ width: "60%", margin: "auto" }}>
        <h1>{name}</h1>
        <div>
          <p>{about}</p>
          <ul style={{ padding: "0px" }}>
            <li>Age: {age}</li>
            <li>Eye color: {eyeColor}</li>
            <li>Balance: {balance}</li>
            <li>Phone: {phone}</li>
            <li>Email: {email}</li>
            <li>Address: {address}</li>
          </ul>
        </div>
      </main>
    </div>
  );
}

export async function getStaticPaths() {
  const paths = peopleJson.map((person) => {
    return {
      params: {
        guid: person.guid,
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const foundPerson = peopleJson.find((person) => person.guid === params.guid);

  return {
    props: foundPerson,
  };
}
