import Head from "next/head";
import peopleJson from "../libs/people-data";
import { useRouter } from "next/router";
import Header from "./components/header";

export default function Home() {
  const router = useRouter();

  const handleOnChange = (guid) => {
    router.push(`/details/${guid}`);
  };

  return (
    <div>
      <Head>
        <title>CA JS Framework</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <div style={{ width: "100%", textAlign: "center" }}>
          {peopleJson.map(({ name, guid }) => {
            return (
              <div key={guid}>
                <h1
                  onClick={() => handleOnChange(guid)}
                  style={{ cursor: "pointer" }}
                >
                  {name}
                </h1>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
}
